### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by kaptcha0** [centridsol/EFCoreAutoMigrator#1]
I desperately need a library like this. I'm using Postgres for a docker application and need to be able to migrate the database programatically. The only problem is I'm also using .Net 6, so it's incompatible with this library. Is there any way for this to be updated to use .Net 5 or 6?

**Comment by walisc** [comment]
Hi there, apologies for the delayed response. I wrote this library for a .Net 3.5 project I was working on back then. Unfortunately I had no plan to update it beyond the project I was working on and I'm currently too busy to look into this now:P I don't think it should be too hard to upgrade though (Unless the Entity Framework Lib has changed drastically) . Have you tried to a simple port/migrate the project to .Net 5 / 6? What errors occurred?

**Comment by walisc** [comment]
@kyro-dev a .net 6.0 version is now available thanks to the work done by @stavroskasidis .Have not had time to extensively test it, but doubt there will be any major issues as it was just an upgrade. Closing this ticket.
